package hackathon.ote.gr.otehackathon.wsdlObjects;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.1
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class CVHabstractContainer extends CVHformElement implements KvmSerializable
{

    
    public ArrayList< CVHformElement> children =new ArrayList<CVHformElement >();
    
    public CVHlayout layout;
    

    
    
    @Override
    public void loadFromSoap(java.lang.Object paramObj,CVHExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);

    }

    @Override
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,CVHExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("children"))
        {
            if(obj!=null)
            {
                if(this.children==null)
                {
                    this.children = new java.util.ArrayList< CVHformElement>();
                }
                java.lang.Object j =obj;
                CVHformElement j1= (CVHformElement)__envelope.get(j,CVHformElement.class,false);
                this.children.add(j1);
            }
            return true;
        }
        if (info.name.equals("layout"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.layout = (CVHlayout)__envelope.get(j,CVHlayout.class,false);
            }
            return true;
        }
        return super.loadProperty(info,soapObject,__envelope);
    }
    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex>=count+0 && propertyIndex < count+0+this.children.size())
        {
            java.lang.Object children = this.children.get(propertyIndex-(count+0));
            return children!=null?children:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==count+0+this.children.size())
        {
            return this.layout!=null?this.layout:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+1+children.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex>=count+0 && propertyIndex < count+0+this.children.size())
        {
            info.type = CVHformElement.class;
            info.name = "children";
            info.namespace= "";
        }
        if(propertyIndex==count+0+this.children.size())
        {
            info.type = CVHlayout.class;
            info.name = "layout";
            info.namespace= "";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

