package hackathon.ote.gr.otehackathon.wsdlObjects;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.1
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class CVHcloseCase extends AttributeContainer implements KvmSerializable
{

    
    public String wsToken;
    
    public ArrayList< CVHmetaProperty> metaData =new ArrayList<CVHmetaProperty >();
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,CVHExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,CVHExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("wsToken"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.wsToken = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.wsToken = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("metaData"))
        {
            if(obj!=null)
            {
                if(this.metaData==null)
                {
                    this.metaData = new java.util.ArrayList< CVHmetaProperty>();
                }
                java.lang.Object j =obj;
                CVHmetaProperty j1= (CVHmetaProperty)__envelope.get(j,CVHmetaProperty.class,false);
                this.metaData.add(j1);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return wsToken;
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.metaData.size())
        {
            java.lang.Object metaData = this.metaData.get(propertyIndex-(1));
            return metaData!=null?metaData:SoapPrimitive.NullNilElement;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 1+metaData.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "wsToken";
            info.namespace= "";
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.metaData.size())
        {
            info.type = CVHmetaProperty.class;
            info.name = "metaData";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

