package hackathon.ote.gr.otehackathon.wsdlObjects;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.1
//
// Created by Quasar Development 
//
//---------------------------------------------------




import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class CVHDiagnosticServiceSoapBinding
{
    interface CVHIWcfMethod
    {
        CVHExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(CVHExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="https://solvrs1.central-domain.root.ote.gr/helpdesk/webservice/diag";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    CVHIServiceEvents callback;
    public CVHDiagnosticServiceSoapBinding(){}

    public CVHDiagnosticServiceSoapBinding (CVHIServiceEvents callback)
    {
        this.callback = callback;
    }
    public CVHDiagnosticServiceSoapBinding(CVHIServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public CVHDiagnosticServiceSoapBinding(CVHIServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected CVHExtendedSoapSerializationEnvelope createEnvelope()
    {
        CVHExtendedSoapSerializationEnvelope envelope= new CVHExtendedSoapSerializationEnvelope(CVHExtendedSoapSerializationEnvelope.VER11);
            return envelope;
    }
    
    protected java.util.List sendRequest(String methodName,CVHExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport ,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile )throws java.lang.Exception
    {
        if(transport instanceof com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE )
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }
        else
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }  
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,CVHExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj,false);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
       }

       return null;
    }

        
    public CVHtopology getTopology(final String wsToken,final String topologyId ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (CVHtopology)execute(new CVHIWcfMethod()
        {
            @Override
            public CVHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CVHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://diagnostic.ws.solvatio.iisy.com/", "getTopology");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="wsToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(wsToken);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="topologyId";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(topologyId);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CVHExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CVHtopology)getResult(CVHtopology.class,__result,"return",__envelope);
            }
        },"urn:GetTopology",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, CVHOperationResult< CVHtopology>> getTopologyAsync(final String wsToken,final String topologyId)
    {
        return executeAsync(new CVHFunctions.IFunc< CVHtopology>() {
            public CVHtopology Func() throws java.lang.Exception {
                return getTopology( wsToken,topologyId);
            }
        },"getTopology");
    }
    
    public CVHsessionState resumeCase(final CVHresumeCase resumeCase ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (CVHsessionState)execute(new CVHIWcfMethod()
        {
            @Override
            public CVHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CVHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://diagnostic.ws.solvatio.iisy.com/","resumeCase",new CVHresumeCase().getClass());
                __envelope.setOutputSoapObject(resumeCase);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CVHExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CVHsessionState)getResult(CVHsessionState.class,__result,"return",__envelope);
            }
        },"urn:ResumeCase",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, CVHOperationResult< CVHsessionState>> resumeCaseAsync(final CVHresumeCase resumeCase)
    {
        return executeAsync(new CVHFunctions.IFunc< CVHsessionState>() {
            public CVHsessionState Func() throws java.lang.Exception {
                return resumeCase( resumeCase);
            }
        },"resumeCase");
    }
    
    public void closeCase(final CVHcloseCase closeCase ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        execute(new CVHIWcfMethod()
        {
            @Override
            public CVHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CVHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://diagnostic.ws.solvatio.iisy.com/","closeCase",new CVHcloseCase().getClass());
                __envelope.setOutputSoapObject(closeCase);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CVHExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return null;
            }
        },"urn:CloseCase",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, CVHOperationResult< Void>> closeCaseAsync(final CVHcloseCase closeCase)
    {
        return executeAsync(new CVHFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                closeCase( closeCase);
                return null;
            }
        },"closeCase") ;
    }
    
    public CVHformPage getForms(final String wsToken,final String processId ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (CVHformPage)execute(new CVHIWcfMethod()
        {
            @Override
            public CVHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CVHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://diagnostic.ws.solvatio.iisy.com/", "getForms");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="wsToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(wsToken);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="processId";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(processId!=null?processId:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CVHExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CVHformPage)getResult(CVHformPage.class,__result,"return",__envelope);
            }
        },"urn:GetForms",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, CVHOperationResult< CVHformPage>> getFormsAsync(final String wsToken,final String processId)
    {
        return executeAsync(new CVHFunctions.IFunc< CVHformPage>() {
            public CVHformPage Func() throws java.lang.Exception {
                return getForms( wsToken,processId);
            }
        },"getForms");
    }
    
    public CVHevents getEvents(final String wsToken,final String processId ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (CVHevents)execute(new CVHIWcfMethod()
        {
            @Override
            public CVHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CVHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://diagnostic.ws.solvatio.iisy.com/", "getEvents");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="wsToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(wsToken);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="processId";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(processId);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CVHExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CVHevents)getResult(CVHevents.class,__result,"return",__envelope);
            }
        },"urn:GetEvents",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, CVHOperationResult< CVHevents>> getEventsAsync(final String wsToken,final String processId)
    {
        return executeAsync(new CVHFunctions.IFunc< CVHevents>() {
            public CVHevents Func() throws java.lang.Exception {
                return getEvents( wsToken,processId);
            }
        },"getEvents");
    }
    
    public CVHsessionState submitForms(final CVHsubmitForms submitForms ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (CVHsessionState)execute(new CVHIWcfMethod()
        {
            @Override
            public CVHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CVHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://diagnostic.ws.solvatio.iisy.com/","submitForms",new CVHsubmitForms().getClass());
                __envelope.setOutputSoapObject(submitForms);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CVHExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CVHsessionState)getResult(CVHsessionState.class,__result,"return",__envelope);
            }
        },"urn:SubmitForms",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, CVHOperationResult< CVHsessionState>> submitFormsAsync(final CVHsubmitForms submitForms)
    {
        return executeAsync(new CVHFunctions.IFunc< CVHsessionState>() {
            public CVHsessionState Func() throws java.lang.Exception {
                return submitForms( submitForms);
            }
        },"submitForms");
    }
    
    public CVHprocessMenuForm getProcessMenu(final String wsToken,final String menuFormId ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (CVHprocessMenuForm)execute(new CVHIWcfMethod()
        {
            @Override
            public CVHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CVHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://diagnostic.ws.solvatio.iisy.com/", "getProcessMenu");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="wsToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(wsToken);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="menuFormId";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(menuFormId!=null?menuFormId:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CVHExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CVHprocessMenuForm)getResult(CVHprocessMenuForm.class,__result,"return",__envelope);
            }
        },"urn:GetProcessMenu",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, CVHOperationResult< CVHprocessMenuForm>> getProcessMenuAsync(final String wsToken,final String menuFormId)
    {
        return executeAsync(new CVHFunctions.IFunc< CVHprocessMenuForm>() {
            public CVHprocessMenuForm Func() throws java.lang.Exception {
                return getProcessMenu( wsToken,menuFormId);
            }
        },"getProcessMenu");
    }
    
    public CVHappForm getAppForm(final String wsToken,final String formId ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (CVHappForm)execute(new CVHIWcfMethod()
        {
            @Override
            public CVHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CVHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://diagnostic.ws.solvatio.iisy.com/", "getAppForm");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="wsToken";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(wsToken);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="formId";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(formId);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CVHExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CVHappForm)getResult(CVHappForm.class,__result,"return",__envelope);
            }
        },"urn:GetAppForm",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, CVHOperationResult< CVHappForm>> getAppFormAsync(final String wsToken,final String formId)
    {
        return executeAsync(new CVHFunctions.IFunc< CVHappForm>() {
            public CVHappForm Func() throws java.lang.Exception {
                return getAppForm( wsToken,formId);
            }
        },"getAppForm");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public void closeSession(final String closeSession ) throws java.lang.Exception
    {
        /*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public android.os.AsyncTask< Void, Void, CVHOperationResult< Void>> closeSessionAsync(final String closeSession)
    {
        return executeAsync(new CVHFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                closeSession( closeSession);
                return null;
            }
        },"closeSession") ;
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public String rollbackProcess(final String wsToken,final String steps,final String processId ) throws java.lang.Exception
    {
        /*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public android.os.AsyncTask< Void, Void, CVHOperationResult< String>> rollbackProcessAsync(final String wsToken,final String steps,final String processId)
    {
        return executeAsync(new CVHFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return rollbackProcess( wsToken,steps,processId);
            }
        },"rollbackProcess");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public void submitFeedback(final String wsToken,final String feedback,final String processId,final String context ) throws java.lang.Exception
    {
        /*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public android.os.AsyncTask< Void, Void, CVHOperationResult< Void>> submitFeedbackAsync(final String wsToken,final String feedback,final String processId,final String context)
    {
        return executeAsync(new CVHFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                submitFeedback( wsToken,feedback,processId,context);
                return null;
            }
        },"submitFeedback") ;
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public String getSessionState(final String wsToken ) throws java.lang.Exception
    {
        /*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public android.os.AsyncTask< Void, Void, CVHOperationResult< String>> getSessionStateAsync(final String wsToken)
    {
        return executeAsync(new CVHFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return getSessionState( wsToken);
            }
        },"getSessionState");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public String startProcess(final String startProcess ) throws java.lang.Exception
    {
        /*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public android.os.AsyncTask< Void, Void, CVHOperationResult< String>> startProcessAsync(final String startProcess)
    {
        return executeAsync(new CVHFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return startProcess( startProcess);
            }
        },"startProcess");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public void setLocale(final String wsToken,final String locale ) throws java.lang.Exception
    {
        /*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public android.os.AsyncTask< Void, Void, CVHOperationResult< Void>> setLocaleAsync(final String wsToken,final String locale)
    {
        return executeAsync(new CVHFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                setLocale( wsToken,locale);
                return null;
            }
        },"setLocale") ;
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public String startCase(final String startCase ) throws java.lang.Exception
    {
        /*This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.*/
        throw new java.lang.UnsupportedOperationException("This feature is available in Premium account. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.");
    }
    
	/**
	* This method is available in Premium account only. To test if generated classes work correctly with your webservice, please use different method. Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
	*/
    public android.os.AsyncTask< Void, Void, CVHOperationResult< String>> startCaseAsync(final String startCase)
    {
        return executeAsync(new CVHFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return startCase( startCase);
            }
        },"startCase");
    }

    
    protected java.lang.Object execute(CVHIWcfMethod wcfMethod,String methodName,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        CVHExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport,profile);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);    
                    
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
    protected < T> android.os.AsyncTask< Void, Void, CVHOperationResult< T>>  executeAsync(final CVHFunctions.IFunc< T> func, final String methodName)
    {
        return new android.os.AsyncTask< Void, Void, CVHOperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected CVHOperationResult< T> doInBackground(Void... params) {
                CVHOperationResult< T> result = new CVHOperationResult< T>();
                try
                {
                    result.MethodName=methodName;
                    result.Result= func.Func();
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(CVHOperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
    protected java.lang.Exception convertToException(org.ksoap2.SoapFault fault,CVHExtendedSoapSerializationEnvelope envelope)
    {
        org.ksoap2.SoapFault newException = fault;

        if(fault.detail!=null && fault.detail.getChildCount()>0)
        {
            Element detailsNode=(Element)fault.detail.getChild(0);
            try
            {
                SoapObject exceptionObject = null;
                exceptionObject=envelope.GetExceptionDetail(detailsNode,"http://diagnostic.ws.solvatio.iisy.com/","TopologyNotFoundFault");
                if (exceptionObject != null)
                {
                    CVHTopologyNotFoundFault ex=new CVHTopologyNotFoundFault();
                    ex.loadFromSoap(exceptionObject,envelope);
                    newException = ex;
                }
                exceptionObject=envelope.GetExceptionDetail(detailsNode,"http://diagnostic.ws.solvatio.iisy.com/","DiagnosticServiceFault");
                if (exceptionObject != null)
                {
                    CVHDiagnosticServiceFault ex=new CVHDiagnosticServiceFault();
                    ex.loadFromSoap(exceptionObject,envelope);
                    newException = ex;
                }
                exceptionObject=envelope.GetExceptionDetail(detailsNode,"http://diagnostic.ws.solvatio.iisy.com/","ValidationFault");
                if (exceptionObject != null)
                {
                    CVHValidationFault ex=new CVHValidationFault();
                    ex.loadFromSoap(exceptionObject,envelope);
                    newException = ex;
                }
            }
            catch (java.lang.Exception e)
            {
                e.printStackTrace();
            }
            newException.detail=fault.detail;
            newException.faultactor=fault.faultactor;
            newException.faultcode=fault.faultcode;
            newException.faultstring=fault.faultstring;
            newException.version=fault.version;
        }
        return newException;
    }
}


