package hackathon.ote.gr.otehackathon.wsdlObjects;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.1
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class CVHformElement extends AttributeContainer implements KvmSerializable
{

    
    public CVHlayoutConstraints layoutConstraints;
    
    public ArrayList< String> styles =new ArrayList<String >();
    
    public Boolean visible=false;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,CVHExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,CVHExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("layoutConstraints"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.layoutConstraints = (CVHlayoutConstraints)__envelope.get(j,CVHlayoutConstraints.class,false);
            }
            return true;
        }
        if (info.name.equals("styles"))
        {
            if(obj!=null)
            {
                if(this.styles==null)
                {
                    this.styles = new java.util.ArrayList< String>();
                }
                java.lang.Object j =obj;
                String j1= j.toString();
                this.styles.add(j1);
            }
            return true;
        }
        if (info.name.equals("visible"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.visible = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.visible = (Boolean)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.layoutConstraints!=null?this.layoutConstraints:SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.styles.size())
        {
            java.lang.Object styles = this.styles.get(propertyIndex-(1));
            return styles!=null?styles:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==1+this.styles.size())
        {
            return visible;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2+styles.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = CVHlayoutConstraints.class;
            info.name = "layoutConstraints";
            info.namespace= "";
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.styles.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "styles";
            info.namespace= "";
        }
        if(propertyIndex==1+this.styles.size())
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "visible";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

