package hackathon.ote.gr.otehackathon.wsdlObjects;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.1
//
// Created by Quasar Development 
//
//---------------------------------------------------



public interface CVHIServiceEvents
{
    public void Starting();
    public void Completed(CVHOperationResult result);
}
