package hackathon.ote.gr.otehackathon.wsdlObjects;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.1
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class CVHprocessCategory extends CVHabstractMenuItem implements KvmSerializable
{

    
    public String icon;
    
    public ArrayList< CVHabstractMenuItem> items =new ArrayList<CVHabstractMenuItem >();
    

    
    
    @Override
    public void loadFromSoap(java.lang.Object paramObj,CVHExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);

    }

    @Override
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,CVHExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("icon"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.icon = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.icon = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("items"))
        {
            if(obj!=null)
            {
                if(this.items==null)
                {
                    this.items = new java.util.ArrayList< CVHabstractMenuItem>();
                }
                java.lang.Object j =obj;
                CVHabstractMenuItem j1= (CVHabstractMenuItem)__envelope.get(j,CVHabstractMenuItem.class,false);
                this.items.add(j1);
            }
            return true;
        }
        return super.loadProperty(info,soapObject,__envelope);
    }
    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.icon!=null?this.icon:SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=count+1 && propertyIndex < count+1+this.items.size())
        {
            java.lang.Object items = this.items.get(propertyIndex-(count+1));
            return items!=null?items:SoapPrimitive.NullNilElement;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+1+items.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "icon";
            info.namespace= "";
        }
        if(propertyIndex>=count+1 && propertyIndex < count+1+this.items.size())
        {
            info.type = CVHabstractMenuItem.class;
            info.name = "items";
            info.namespace= "";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

