package hackathon.ote.gr.otehackathon.wsdlObjects;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.1
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class CVHquestionForm extends CVHform implements KvmSerializable
{

    
    public String conclusion;
    
    public String introduction;
    
    public String prompt;
    
    public Boolean required=false;
    
    public String title;
    
    public CVHvalidator validator;
    

    
    
    @Override
    public void loadFromSoap(java.lang.Object paramObj,CVHExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        super.loadFromSoap(paramObj, __envelope);

    }

    @Override
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,CVHExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("conclusion"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.conclusion = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.conclusion = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("introduction"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.introduction = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.introduction = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("prompt"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.prompt = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.prompt = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("required"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.required = new Boolean(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.required = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("title"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.title = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.title = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("validator"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.validator = (CVHvalidator)__envelope.get(j,CVHvalidator.class,false);
            }
            return true;
        }
        return super.loadProperty(info,soapObject,__envelope);
    }
    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.conclusion!=null?this.conclusion:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+1)
        {
            return this.introduction!=null?this.introduction:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+2)
        {
            return this.prompt!=null?this.prompt:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+3)
        {
            return required;
        }
        if(propertyIndex==count+4)
        {
            return title;
        }
        if(propertyIndex==count+5)
        {
            return this.validator!=null?this.validator:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "conclusion";
            info.namespace= "";
        }
        if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "introduction";
            info.namespace= "";
        }
        if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "prompt";
            info.namespace= "";
        }
        if(propertyIndex==count+3)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "required";
            info.namespace= "";
        }
        if(propertyIndex==count+4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "title";
            info.namespace= "";
        }
        if(propertyIndex==count+5)
        {
            info.type = CVHvalidator.class;
            info.name = "validator";
            info.namespace= "";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

