package hackathon.ote.gr.otehackathon.wsdlObjects;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.1
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class CVHresumeCase extends AttributeContainer implements KvmSerializable
{

    
    public String caseId;
    
    public CVHuserData user;
    
    public CVHlocale locale;
    
    public ArrayList< CVHstartParameter> startParameters =new ArrayList<CVHstartParameter >();
    
    public String applicationId;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,CVHExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,CVHExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("caseId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.caseId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.caseId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("user"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.user = (CVHuserData)__envelope.get(j,CVHuserData.class,false);
            }
            return true;
        }
        if (info.name.equals("locale"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.locale = (CVHlocale)__envelope.get(j,CVHlocale.class,false);
            }
            return true;
        }
        if (info.name.equals("startParameters"))
        {
            if(obj!=null)
            {
                if(this.startParameters==null)
                {
                    this.startParameters = new java.util.ArrayList< CVHstartParameter>();
                }
                java.lang.Object j =obj;
                CVHstartParameter j1= (CVHstartParameter)__envelope.get(j,CVHstartParameter.class,false);
                this.startParameters.add(j1);
            }
            return true;
        }
        if (info.name.equals("applicationId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.applicationId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.applicationId = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return caseId;
        }
        if(propertyIndex==1)
        {
            return user;
        }
        if(propertyIndex==2)
        {
            return locale;
        }
        if(propertyIndex>=3 && propertyIndex < 3+this.startParameters.size())
        {
            java.lang.Object startParameters = this.startParameters.get(propertyIndex-(3));
            return startParameters!=null?startParameters:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==3+this.startParameters.size())
        {
            return this.applicationId!=null?this.applicationId:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4+startParameters.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "caseId";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = CVHuserData.class;
            info.name = "user";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = CVHlocale.class;
            info.name = "locale";
            info.namespace= "";
        }
        if(propertyIndex>=3 && propertyIndex < 3+this.startParameters.size())
        {
            info.type = CVHstartParameter.class;
            info.name = "startParameters";
            info.namespace= "";
        }
        if(propertyIndex==3+this.startParameters.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "applicationId";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

