package hackathon.ote.gr.otehackathon.wsdlObjects;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.1
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class CVHsessionState extends AttributeContainer implements KvmSerializable
{

    
    public String caseId;
    
    public ArrayList< CVHprocessState> processStates =new ArrayList<CVHprocessState >();
    
    public String token;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,CVHExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,CVHExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("caseId"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.caseId = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.caseId = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("processStates"))
        {
            if(obj!=null)
            {
                if(this.processStates==null)
                {
                    this.processStates = new java.util.ArrayList< CVHprocessState>();
                }
                java.lang.Object j =obj;
                CVHprocessState j1= (CVHprocessState)__envelope.get(j,CVHprocessState.class,false);
                this.processStates.add(j1);
            }
            return true;
        }
        if (info.name.equals("token"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.token = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.token = (String)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return caseId;
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.processStates.size())
        {
            java.lang.Object processStates = this.processStates.get(propertyIndex-(1));
            return processStates!=null?processStates:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==1+this.processStates.size())
        {
            return token;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2+processStates.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "caseId";
            info.namespace= "";
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.processStates.size())
        {
            info.type = CVHprocessState.class;
            info.name = "processStates";
            info.namespace= "";
        }
        if(propertyIndex==1+this.processStates.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "token";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

