package hackathon.ote.gr.otehackathon.wsdlObjects;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.1
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class CVHuserData extends AttributeContainer implements KvmSerializable
{

    
    public String name;
    
    public String organizationUnit;
    
    public String displayName;
    
    public String email;
    
    public ArrayList< String> roles =new ArrayList<String >();
    
    public CVHuserData_extendedData extendedData;
    private transient java.lang.Object __source;    
    

    
    
    
    public void loadFromSoap(java.lang.Object paramObj,CVHExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,CVHExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("name"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.name = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.name = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("organizationUnit"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.organizationUnit = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.organizationUnit = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("displayName"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.displayName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.displayName = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("email"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.email = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.email = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("roles"))
        {
            if(obj!=null)
            {
                if(this.roles==null)
                {
                    this.roles = new java.util.ArrayList< String>();
                }
                java.lang.Object j =obj;
                String j1= j.toString();
                this.roles.add(j1);
            }
            return true;
        }
        if (info.name.equals("extendedData"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.extendedData = (CVHuserData_extendedData)__envelope.get(j,CVHuserData_extendedData.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return name;
        }
        if(propertyIndex==1)
        {
            return this.organizationUnit!=null?this.organizationUnit:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.displayName!=null?this.displayName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.email!=null?this.email:SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=4 && propertyIndex < 4+this.roles.size())
        {
            java.lang.Object roles = this.roles.get(propertyIndex-(4));
            return roles!=null?roles:SoapPrimitive.NullNilElement;
        }
        if(propertyIndex==4+this.roles.size())
        {
            return this.extendedData!=null?this.extendedData:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 5+roles.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "name";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "organizationUnit";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "displayName";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "email";
            info.namespace= "";
        }
        if(propertyIndex>=4 && propertyIndex < 4+this.roles.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "roles";
            info.namespace= "";
        }
        if(propertyIndex==4+this.roles.size())
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "extendedData";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

